# Generated by Django 5.1.3 on 2024-11-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='imageurl',
        ),
    ]
