# Generated by Django 5.1.3 on 2024-11-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_price_item_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='item',
            name='md5_hash',
            field=models.CharField(default='hasda', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='phash',
            field=models.CharField(default='ffss', max_length=64),
            preserve_default=False,
        ),
    ]
