# Generated by Django 5.1.3 on 2024-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_uploaditem_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(default='dasd'),
            preserve_default=False,
        ),
    ]
