# Generated by Django 5.1.3 on 2024-11-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadItem',
        ),
    ]
